package:
  name: psi4
  version: 1.3.appveyor1088

source:
  url: https://ci.appveyor.com/api/buildjobs/rhbiy4mgms0kdpex/artifacts/psi4.zip
  md5: 48946cadada17aad4a0e8389d3fc7499

requirements:
  run:
    - deepdiff
    - intel-openmp=2018.0.3
    - mkl-devel=2018.0.3
    - numpy
    - python=3.6.*
    - pytest
    - vc

build:
  number: 0
  script:
    - xcopy /f /i /s /exclude:%RECIPE_DIR%\exclude.txt lib\psi4 %SP_DIR%\psi4
    # TODO find a better place for Psi4 data
    - xcopy /f /i /s share\psi4\basis %PREFIX%\Lib\share\psi4\basis
    - xcopy /f /i /s share\psi4\plugin %PREFIX%\Lib\share\psi4\plugin
    #- xcopy /f /i /s share\psi4\basis %PREFIX%\Lib\share\psi4\quadratures
    - copy /y C:\Windows\System32\msvcp140d.dll %PREFIX%
    - copy /y C:\Windows\System32\vcomp140d.dll %PREFIX%
    - copy /y C:\Windows\System32\vcruntime140d.dll %PREFIX%
    - copy /y C:\Windows\System32\ucrtbased.dll %PREFIX%

test:
  commands:
    - python -c "import psi4; print(psi4)"
    #- pytest -v %CONDA_PREFIX%\Lib\site-packages\psi4\tests\test_psi4.py
    #- python -c "import psi4; psi4.test()"
