package:
  name: psi4
  version: 0.0.0

source:
  path: {{ INSTALL_DIR }}

requirements:
  run:
    - deepdiff
    - intel-openmp=2018.0.3
    - mkl=2018.0.3
    - networkx
    - numpy
    - pytest
    - qcelemental

build:
  number: 0
  script:
    - xcopy /f /i /s /exclude:%RECIPE_DIR%\exclude.txt lib\psi4 %SP_DIR%\psi4
    # TODO find a better place for Psi4 data
    - xcopy /f /i /s share\psi4\basis %PREFIX%\Lib\share\psi4\basis
    - xcopy /f /i /s share\psi4\plugin %PREFIX%\Lib\share\psi4\plugin
    - xcopy /f /i /s share\psi4\basis %PREFIX%\Lib\share\psi4\quadratures
    - copy /y C:\Windows\System32\msvcp140d.dll %PREFIX%
    - copy /y C:\Windows\System32\vcomp140d.dll %PREFIX%
    - copy /y C:\Windows\System32\vcruntime140d.dll %PREFIX%
    - copy /y C:\Windows\System32\ucrtbased.dll %PREFIX%

test:
  commands:
    - python -c "import psi4; print(psi4)"
    - python -c "import psi4; assert psi4.test() == 0"
