{% set data = load_setup_py_data(setup_file='conda/_conda_vers.py') %}

package:
  name: psi4
  version: {{ data.get('version') }}
  #version: "0.0.0"

source:
  path: ../..

requirements:
  run:
    - deepdiff
    - intel-openmp=2018.0.3
    - mkl=2018.0.3
    - networkx
    - numpy
    - pytest
    - python=3.6
    - qcelemental

build:
  number: 0
  string: "debug"
  script:
    - echo __pycache__ > exclude.txt
    - dir
    - xcopy /f /i /s /exclude:exclude.txt {{INSTALL_DIR}}\lib\psi4 {{SP_DIR}}\psi4
    - xcopy /f /i /s {{INSTALL_DIR}}\share\psi4\basis       {{PREFIX}}\Lib\share\psi4\basis
    - xcopy /f /i /s {{INSTALL_DIR}}\share\psi4\plugin      {{PREFIX}}\Lib\share\psi4\plugin
    - xcopy /f /i /s {{INSTALL_DIR}}\share\psi4\quadratures {{PREFIX}}\Lib\share\psi4\quadratures
    - copy /y {{SYSTEMROOT}}\System32\msvcp140d.dll     {{PREFIX}}
    - copy /y {{SYSTEMROOT}}\System32\vcomp140d.dll     {{PREFIX}}
    - copy /y {{SYSTEMROOT}}\System32\vcruntime140d.dll {{PREFIX}}
    - copy /y {{SYSTEMROOT}}\System32\ucrtbased.dll     {{PREFIX}}

test:
  commands:
    - python -c "import psi4; print(psi4)"
    - python -c "import psi4; assert psi4.test('quick') == 0"
