platform:
  - x64

image:
  - Visual Studio 2015
#  - Visual Studio 2017

configuration:
  - Debug

install:
  - set CONDA_ENV=build
  - C:\Miniconda3-x64\Scripts\activate base
  - conda config --set always_yes yes
  - conda create --channel conda-forge
                 --name %CONDA_ENV%
                 deepdiff
                 mkl-devel
                 mpmath
                 networkx
                 ninja
                 numpy
                 pthreads-win32
                 pytest
  - conda clean --all
  - activate %CONDA_ENV%
  - conda list
before_build:
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - set SOURCE_FOLDER=%APPVEYOR_BUILD_FOLDER%
  - set BUILD_FOLDER=%SOURCE_FOLDER%\build
  - set INSTALL_FOLDER=%SOURCE_FOLDER%\install
  - mkdir %BUILD_FOLDER% & cd %BUILD_FOLDER%
  # TODO OpenMP
  # TODO -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON
  # TODO /D_USE_MATH_DEFINES
  # TODO /EHs
  # TODO /bigobj
  - cmake -G Ninja
          -DCMAKE_BUILD_TYPE=%CONFIGURATION%
          -DCMAKE_INSTALL_PREFIX=%INSTALL_FOLDER%
          -DCMAKE_C_FLAGS="/wd4018 /wd4101 /wd4996"
          -DCMAKE_CXX_FLAGS="/D_USE_MATH_DEFINES /EHs /bigobj /wd4251 /wd4267"
          -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON
          -DENABLE_OPENMP=OFF
          -DENABLE_XHOST=OFF
          -DMAX_AM_ERI=5
          %SOURCE_FOLDER%

build_script:
  - cmake --build .
          --config %CONFIGURATION%
          -- -j %NUMBER_OF_PROCESSORS%

after_build:
  - cmake --build .
          --config %CONFIGURATION%
          --target install
          -- -j %NUMBER_OF_PROCESSORS%

before_test:
  - set PYTHONPATH=%INSTALL_FOLDER%\lib
  - python -c "import psi4; print(psi4)"
  # TODO psi4.bat
  # TODO set PATH
  - python %INSTALL_FOLDER%\bin\psi4 --version

test_script:
  - python %INSTALL_FOLDER%\lib\psi4\tests\test_psi4.py # TODO remove
  - python %INSTALL_FOLDER%\bin\psi4 %SOURCE_FOLDER%\tests\tu1-h2o-energy\input.dat

on_success:
  - ctest --build-config %CONFIGURATION%
          --label-regex quick
          --output-on-failure
          --parallel %NUMBER_OF_PROCESSORS%
  - python %INSTALL_FOLDER%\bin\psi4 --test

cache:
  - C:\Miniconda3-x64\pkgs

artifacts:
  - path: install
    name: psi4