platform:
  - x64

image:
  - Visual Studio 2015
#  - Visual Studio 2017

configuration:
  - Debug

install:
  - C:\Miniconda36-x64\Scripts\conda create --name build --yes numpy mpmath mkl-devel networkx pytest
  - C:\Miniconda36-x64\Scripts\activate build
  - C:\Miniconda36-x64\Scripts\conda install --channel conda-forge --yes pthreads-win32 deepdiff
  - C:\Miniconda36-x64\Scripts\conda list
  - set MATH_ROOT=C:\Miniconda36-x64\envs\build\Library

before_build:
  - set INSTALL_PREFX=C:\projects\psi4\install
  - mkdir build & cd build
  - cmake -A %PLATFORM%
          -DMAX_AM_ERI=3
          -DENABLE_XHOST=OFF
          -DENABLE_OPENMP=OFF
          -DCMAKE_BUILD_TYPE=%CONFIGURATION%
          -DCMAKE_C_FLAGS="/wd4018 /wd4101 /wd4996"
          -DCMAKE_CXX_FLAGS="/D_USE_MATH_DEFINES /EHs /bigobj /wd4251 /wd4267"
          -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON
          -DCMAKE_INSTALL_PREFIX=%INSTALL_PREFX%
          ..

build_script:
  - cmake --build .
          --config %CONFIGURATION%
          

after_build:
  - cmake --build .
          --config %CONFIGURATION%
          --target install

before_test:
  - cd C:\
  - set PYTHONPATH=%INSTALL_PREFX%\lib
  - python.exe -c "import psi4; print(psi4)"

test_script:
  - python.exe %INSTALL_PREFX%\lib\psi4\tests\test_psi4.py
#  - python.exe -c "import psi4; psi4.test()"
#  - ctest --build-config %CONFIGURATION%
#          --verbose

cache:
  - C:\Miniconda36-x64\pkgs

artifacts:
  - path: install
    name: psi4