platform:
  - x64

image:
  - Visual Studio 2015
#  - Visual Studio 2017

configuration:
  - Debug

install:
  # TODO general conda
  # TODO update conda
  - C:\Miniconda36-x64\Scripts\conda create --name build --yes numpy mpmath mkl-devel networkx pytest
  - C:\Miniconda36-x64\Scripts\activate build
  - C:\Miniconda36-x64\Scripts\conda install --channel conda-forge --yes pthreads-win32 deepdiff
  - C:\Miniconda36-x64\Scripts\conda list
  - C:\Miniconda36-x64\Scripts\conda clean --all --yes
  - set MATH_ROOT=C:\Miniconda36-x64\envs\build\Library # TODO check

before_build:
  - set SOURCE_FOLDER=%APPVEYOR_BUILD_FOLDER%
  - set BUILD_FOLDER=%SOURCE_FOLDER%\build
  - set INSTALL_FOLDER=%SOURCE_FOLDER%\install
  - mkdir %BUILD_FOLDER% & cd %BUILD_FOLDER%
  # TODO OpenMP
  # TODO CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON
  # TODO /D_USE_MATH_DEFINES
  # TODO /EHs
  # TODO /bigobj
  - cmake -A %PLATFORM%
          -DCMAKE_BUILD_TYPE=%CONFIGURATION%
          -DCMAKE_INSTALL_PREFIX=%INSTALL_FOLDER%
          -DCMAKE_C_FLAGS="/wd4018 /wd4101 /wd4996"
          -DCMAKE_CXX_FLAGS="/D_USE_MATH_DEFINES /EHs /bigobj /wd4251 /wd4267"
          -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON
          -DENABLE_OPENMP=OFF
          -DENABLE_XHOST=OFF
          -DMAX_AM_ERI=5
          %SOURCE_FOLDER%

build_script:
  # TODO Paralle build
  - cmake --build .
          --config %CONFIGURATION%
          -- /maxcpucount:%NUMBER_OF_PROCESSORS%

after_build:
  # TODO Paralle build
  - cmake --build .
          --config %CONFIGURATION%
          --target install
          -- /maxcpucount:%NUMBER_OF_PROCESSORS%

before_test:
  - set PYTHONPATH=%INSTALL_FOLDER%\lib
  - python -c "import psi4; print(psi4)"
  # TODO psi4.bat
  # TODO set PATH
  - python %INSTALL_FOLDER%\bin\psi4 --version

test_script:
  - python %INSTALL_FOLDER%\lib\psi4\tests\test_psi4.py # TODO remove
  - python %INSTALL_FOLDER%\bin\psi4 %SOURCE_FOLDER%\tests\tu1-h2o-energy\input.dat

#on_success:
#  - ctest --build-config %CONFIGURATION%
#          --label-regex quick
#          --output-on-failure
#          --parallel %NUMBER_OF_PROCESSORS%
#  - python %INSTALL_FOLDER%\bin\psi4 --test

cache:
  - C:\Miniconda36-x64\pkgs

artifacts:
  - path: install
    name: \%APPVEYOR_PROJECT_NAME%