# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'vs2015-win2012r2'

steps:
 
  # Install Chocolatey (https://chocolatey.org/install#install-with-powershellexe)
  - powershell: |
      Set-ExecutionPolicy Bypass -Scope Process -Force
      iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      choco
  
  # Install Miniconda
  - powershell: |
      choco install miniconda3
      conda --version
