# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'vs2015-win2012r2'

steps:
# Python Script
# Run a Python script.
  - task: PythonScript@0
    inputs:
      scriptSource: 'inline'
      #scriptPath: # Required when scriptSource == FilePath
      script: 'print("Hello world!")'
      #arguments: # Optional
      #pythonInterpreter: # Optional
      #workingDirectory: # Optional
      #failOnStderr: false # Optional
