# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'vs2015-win2012r2'

trigger:
  - master

steps:
 
  # Install Chocolatey (https://chocolatey.org/install#install-with-powershellexe)
  - powershell: |
      Set-ExecutionPolicy Bypass -Scope Process -Force
      iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      Write-Host "##vso[task.setvariable variable=PATH]$env:PATH"
      choco --version
    displayName: "Install Chocolatey"

  
  # Install Miniconda
  - powershell: |
      choco install miniconda3 --yes
      $env:PATH = "C:\tools\miniconda3\Scripts;" + $env:PATH
      $env:PATH = "C:\tools\miniconda3\Library\bin;" + $env:PATH
      Write-Host "##vso[task.setvariable variable=PATH]$env:PATH"
      conda --version
    displayName: "Install Miniconda"

  # Create conda enviroment
  # Note: conda activate/deactive doesn't work yet with PowerShell (https://github.com/conda/conda/issues/626)
  - powershell: |
      conda config --set always_yes yes 
      conda install --channel conda-forge `
                    cmake `
                    deepdiff `
                    intel-openmp=2018.0.3 `
                    mkl-devel=2018.0.3 `
                    mpmath `
                    networkx `
                    ninja `
                    numpy `
                    pybind11 `
                    pytest `
                    python=3.6
      conda list
    displayName: "Install conda packages"

  # Install LLVM
  # Note: LLVM distributed by conda is too old
  - powershell: |
      choco install llvm --yes
      $env:PATH = "C:\Program Files\LLVM\bin;" + $env:PATH
      Write-Host "##vso[task.setvariable variable=PATH]$env:PATH"
      clang-cl --version
    displayName: "Install LLVM"

  # Configure
  - powershell: |
      dir
      cmake ${Build.SourcesDirectory}
    workingDirectory: ${Build.BinariesDirectory}
    

  # Build
  
  # Install
  
  # Test
  
  # Package
  
  # Deploy
  
  
