# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'vs2015-win2012r2'

steps:
  # Create and activate a Conda environment.
  - task: CondaEnvironment@1
    inputs:
      #createCustomEnvironment: True
      #environmentName: 'build'
      #packageSpecs: 'python=3.6'
      #updateConda: True
      #installOptions: # Optional
      #createOptions: # Optional
      #cleanEnvironment: # Optional
