# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'vs2015-win2012r2'

steps:
 
  # Install Chocolatey (https://chocolatey.org/install#install-with-powershellexe)
  - powershell: |
      Set-ExecutionPolicy Bypass -Scope Process -Force
      iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      Write-Host "##vso[task.setvariable variable=PATH]$env:PATH"
  
  # Install Miniconda
  - powershell: |
      choco install miniconda3 --yes
      $env:PATH = $env:PATH + "C:\tools\miniconda3\Scripts;"
      Write-Host "##vso[task.setvariable variable=PATH]$env:PATH"
      conda --version
      
  # Install LLVM
  - powershell: |
      choco install llvm --yes
      echo $env:PATH

  - powershell: |
      choco --version
      conda --version
